version: '2'
authtoken: 6qpezv4HgZocnF9iNFGhp_4LSM1FMRWrE4z57fLVqE8
tunnels:
  first-app:
    addr: 3306
    proto: tcp
  second-app:
    addr: 8080
    proto: http
  third-app:
    addr: 9229
    proto: tcp